from enum import StrEnum


class PackState(StrEnum):
    ASSEMBLING = "ASSEMBLING"
    PACKED = "PACKED"
    CANCELLED = "CANCELLED"
    WAITING_WITHDRAWAL = "WAITING_WITHDRAWAL"
    WITHDRAWAL_EXPORTED = "WITHDRAWAL_EXPORTED"
    WITHDRAWN = "WITHDRAWN"
    RETURN_EXPECTED = "RETURN_EXPECTED"
    RETURN_RECEIVED = "RETURN_RECEIVED"
    WAITING_REINTRODUCTION = "WAITING_REINTRODUCTION"
    REINTRODUCTION_EXPORTED = "REINTRODUCTION_EXPORTED"
    REINTRODUCED = "REINTRODUCED"
    NEEDS_RECONCILIATION = "NEEDS_RECONCILIATION"


class CodeState(StrEnum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    OUT_OF_CIRCULATION = "OUT_OF_CIRCULATION"
    RETURN_PENDING = "RETURN_PENDING"
    BLOCKED = "BLOCKED"


class BatchType(StrEnum):
    WITHDRAWAL = "WITHDRAWAL"
    REINTRODUCTION = "REINTRODUCTION"


MANAGER_ROLES = {"admin", "warehouse_manager"}
LABEL_SIZE_ITEM = "S"
LABEL_SIZE_PACK = "M"
LABEL_SIZE_PALLET = "M"
MAX_LABEL_BATCH = 100
